Components
fedgut/Bookstore-CMS pull request #2
Opened 2020-08-19 22:11 UTC by MiguelDP4

- Create books list component
- Create form component
- Create book component
- Create book reducer
- Create book reducer tests
- Create store 
- Pass store as prop to app

2020-08-20 08:25 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [ ] Your actions are missing, let's add them. Example below:
```javascript
export const createBook = (book) => ({
  type: 'CREATE_BOOK',
  book
})
```

- [ ] The main reducer should be placed in `src/actions/index.js` and combine app-specific reducers. See what I mean below:

```javascript
import { combineReducers } from 'redux';
import books from './books';

export default combineReducers({ books })
```

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-08-20 08:25 UTC, suretrust commented on src/components/BooksList.js
> +  const { books } = props;
This `books` props should come from the Redux store using `mapStateToProps`.
* [x] it connects to Redux store and fetches books from the state [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/BooksList/ConnetToRedux.png)
* [x] it uses `mapStateToProps` to fetch books from the `store`

2020-08-20 08:25 UTC, suretrust commented on src/index.js
> +  </Provider>,
You should use `mapStateToProps` to get things from the store, you don't have to pass it directly. Also, you don't need to remove the `React.StrictMode`, you just need to wrap the `App` component with the `Provider` as shown below.
```suggestion
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>,
```

2020-08-22 09:53 UTC, shloch requested changes
## Hello @MiguelDP4 , @fedgut 

We're progressing really good

Just minor things are left as mentioned below

Please let's bring these updates to life

Happy coding

2020-08-22 09:53 UTC, shloch commented on src/components/BooksList.js
> +
this component should be inside the `src/containers`
![folders](https://user-images.githubusercontent.com/40712459/90953475-c23e9d00-e463-11ea-8ccc-ef63e38e4d91.png)

from instructions we have 
- 2 `presentational` components (`App` and `Book`) : they should be in the folder `src/components`
- 02 `container` components (`BooksList` and `BooksForm`) : they should be in the folder `src/containers`

So let's just polish this little detail

2020-08-22 09:53 UTC, shloch commented on src/components/BooksList.js
> +
it should connect to redux store
`import { connect } from "react-redux";`

2020-08-22 09:53 UTC, shloch commented on src/components/BooksList.js
> +
It should use `mapStateToProps` to fetch books from the `store`

2020-08-22 09:53 UTC, shloch commented on src/components/BookForm.js
> +
this component should be placed in `src/containers` folder

2020-08-24 20:39 UTC, bellom approved these changes
## Hi Team :clap:

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-25 18:13 UTC, merged